# Docker startup script for production, development, and testing
# Usage: 
#   .\docker-start.ps1          # Start production environment
#   .\docker-start.ps1 -Dev     # Start development environment (with hot-reload)
#   .\docker-start.ps1 -Test    # Run test suite

param(
    [switch]$Dev,
    [switch]$Test
)

if ($Test) {
    # TEST MODE: Run full test suite
    Write-Host "Starting test suite..." -ForegroundColor Cyan
    Write-Host ""
    
    # Check if test.db exists
    if (Test-Path "backend\tests\test.db") {
        Write-Host "Using existing test.db" -ForegroundColor Green
    } else {
        Write-Host "test.db will be auto-generated by conftest.py" -ForegroundColor Yellow
    }
    
    Write-Host ""
    Write-Host "Running full test suite (192+ tests)..." -ForegroundColor Cyan
    Write-Host "- Backend: 127+ tests (test_tasks.py, test_ai.py, test_database.py, test_integration.py)" -ForegroundColor Gray
    Write-Host "- Frontend: 65+ tests (TaskList, TaskForm, Dashboard)" -ForegroundColor Gray
    Write-Host ""
    
    # Run tests with docker-compose
    docker-compose -f docker-compose.test.yml up --abort-on-container-exit --exit-code-from backend-test
    
    $testResult = $LASTEXITCODE
    
    Write-Host ""
    if ($testResult -eq 0) {
        Write-Host "All tests passed!" -ForegroundColor Green
        Write-Host ""
        Write-Host "View detailed logs:" -ForegroundColor Gray
        Write-Host "  docker-compose -f docker-compose.test.yml logs backend-test" -ForegroundColor Gray
        Write-Host "  docker-compose -f docker-compose.test.yml logs frontend-test" -ForegroundColor Gray
    } else {
        Write-Host "Tests failed. View logs for details:" -ForegroundColor Red
        Write-Host "  docker-compose -f docker-compose.test.yml logs backend-test" -ForegroundColor Gray
        Write-Host "  docker-compose -f docker-compose.test.yml logs frontend-test" -ForegroundColor Gray
    }
    
    Write-Host ""
    Write-Host "Cleanup containers:" -ForegroundColor Gray
    Write-Host "  docker-compose -f docker-compose.test.yml down -v" -ForegroundColor Gray
    Write-Host ""
    
    exit $testResult
    
} elseif ($Dev) {
    # DEVELOPMENT MODE: Hot-reload, mounted volumes
    Write-Host "Starting development environment..." -ForegroundColor Cyan
    Write-Host ""
    Write-Host "Features:" -ForegroundColor Gray
    Write-Host "  - Hot-reload enabled" -ForegroundColor Gray
    Write-Host "  - Code changes reflected immediately" -ForegroundColor Gray
    Write-Host "  - Volumes mounted for live editing" -ForegroundColor Gray
    Write-Host ""
    Write-Host "Services:" -ForegroundColor Gray
    Write-Host "  - Backend:  http://localhost:8000" -ForegroundColor Gray
    Write-Host "  - Frontend: http://localhost:3000" -ForegroundColor Gray
    Write-Host ""
    Write-Host "Press Ctrl+C to stop..." -ForegroundColor Yellow
    Write-Host ""
    
    # Start development environment with docker-compose
    docker-compose up --build
    
    # Cleanup on exit
    Write-Host ""
    Write-Host "Stopping services..." -ForegroundColor Yellow
    docker-compose down
    
} else {
    # PRODUCTION MODE: Optimized build, no volumes
    Write-Host "Starting production environment..." -ForegroundColor Cyan
    Write-Host ""
    Write-Host "Features:" -ForegroundColor Gray
    Write-Host "  - Optimized production build" -ForegroundColor Gray
    Write-Host "  - No hot-reload" -ForegroundColor Gray
    Write-Host "  - Production-ready configuration" -ForegroundColor Gray
    Write-Host ""
    Write-Host "Services:" -ForegroundColor Gray
    Write-Host "  - Backend:  http://localhost:8000" -ForegroundColor Gray
    Write-Host "  - Frontend: http://localhost:3000" -ForegroundColor Gray
    Write-Host ""
    Write-Host "Press Ctrl+C to stop..." -ForegroundColor Yellow
    Write-Host ""
    
    # Start production environment
    docker-compose up --build -d
    
    Write-Host ""
    Write-Host "Services started in detached mode" -ForegroundColor Green
    Write-Host ""
    Write-Host "View logs:" -ForegroundColor Gray
    Write-Host "  docker-compose logs -f" -ForegroundColor Gray
    Write-Host ""
    Write-Host "Stop services:" -ForegroundColor Gray
    Write-Host "  docker-compose down" -ForegroundColor Gray
    Write-Host ""
}
