#!/bin/bash
# Docker startup script for production, development, and testing
# Usage: 
#   ./docker-start.sh          # Start production environment
#   ./docker-start.sh -Dev     # Start development environment (with hot-reload)
#   ./docker-start.sh -Test    # Run test suite

if [ "$1" = "-Test" ]; then
    # TEST MODE: Run full test suite
    echo -e "\033[0;36mStarting test suite...\033[0m"
    echo ""
    
    # Check if test.db exists
    if [ -f "backend/tests/test.db" ]; then
        echo -e "\033[0;32mUsing existing test.db\033[0m"
    else
        echo -e "\033[0;33mtest.db will be auto-generated by conftest.py\033[0m"
    fi
    
    echo ""
    echo -e "\033[0;36mRunning full test suite (192+ tests)...\033[0m"
    echo -e "\033[0;90m- Backend: 127+ tests (test_tasks.py, test_ai.py, test_database.py, test_integration.py)\033[0m"
    echo -e "\033[0;90m- Frontend: 65+ tests (TaskList, TaskForm, Dashboard)\033[0m"
    echo ""
    
    # Run tests with docker-compose
    docker-compose -f docker-compose.test.yml up --abort-on-container-exit --exit-code-from backend-test
    
    TEST_RESULT=$?
    
    echo ""
    if [ $TEST_RESULT -eq 0 ]; then
        echo -e "\033[0;32mAll tests passed!\033[0m"
        echo ""
        echo -e "\033[0;90mView detailed logs:\033[0m"
        echo -e "\033[0;90m  docker-compose -f docker-compose.test.yml logs backend-test\033[0m"
        echo -e "\033[0;90m  docker-compose -f docker-compose.test.yml logs frontend-test\033[0m"
    else
        echo -e "\033[0;31mTests failed. View logs for details:\033[0m"
        echo -e "\033[0;90m  docker-compose -f docker-compose.test.yml logs backend-test\033[0m"
        echo -e "\033[0;90m  docker-compose -f docker-compose.test.yml logs frontend-test\033[0m"
    fi
    
    echo ""
    echo -e "\033[0;90mCleanup containers:\033[0m"
    echo -e "\033[0;90m  docker-compose -f docker-compose.test.yml down -v\033[0m"
    echo ""
    
    exit $TEST_RESULT
    
elif [ "$1" = "-Dev" ]; then
    # DEVELOPMENT MODE: Hot-reload, mounted volumes
    echo -e "\033[0;36mStarting development environment...\033[0m"
    echo ""
    echo -e "\033[0;90mFeatures:\033[0m"
    echo -e "\033[0;90m  - Hot-reload enabled\033[0m"
    echo -e "\033[0;90m  - Code changes reflected immediately\033[0m"
    echo -e "\033[0;90m  - Volumes mounted for live editing\033[0m"
    echo ""
    echo -e "\033[0;90mServices:\033[0m"
    echo -e "\033[0;90m  - Backend:  http://localhost:8000\033[0m"
    echo -e "\033[0;90m  - Frontend: http://localhost:3000\033[0m"
    echo ""
    echo -e "\033[0;33mPress Ctrl+C to stop...\033[0m"
    echo ""
    
    # Start development environment with docker-compose
    docker-compose up --build
    
    # Cleanup on exit
    echo ""
    echo -e "\033[0;33mStopping services...\033[0m"
    docker-compose down
    
else
    # PRODUCTION MODE: Optimized build, no volumes
    echo -e "\033[0;36mStarting production environment...\033[0m"
    echo ""
    echo -e "\033[0;90mFeatures:\033[0m"
    echo -e "\033[0;90m  - Optimized production build\033[0m"
    echo -e "\033[0;90m  - No hot-reload\033[0m"
    echo -e "\033[0;90m  - Production-ready configuration\033[0m"
    echo ""
    echo -e "\033[0;90mServices:\033[0m"
    echo -e "\033[0;90m  - Backend:  http://localhost:8000\033[0m"
    echo -e "\033[0;90m  - Frontend: http://localhost:3000\033[0m"
    echo ""
    echo -e "\033[0;33mPress Ctrl+C to stop...\033[0m"
    echo ""
    
    # Start production environment
    docker-compose up --build -d
    
    echo ""
    echo -e "\033[0;32mServices started in detached mode\033[0m"
    echo ""
    echo -e "\033[0;90mView logs:\033[0m"
    echo -e "\033[0;90m  docker-compose logs -f\033[0m"
    echo ""
    echo -e "\033[0;90mStop services:\033[0m"
    echo -e "\033[0;90m  docker-compose down\033[0m"
    echo ""
fi
